name: CI/CD Workflow

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:

  build-python:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build Python package
      run: python setup.py sdist bdist_wheel
      
    - name: Upload Python package
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: dist/*.whl
        
  build-go:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
        
    - name: Build Go binary
      run: go build -v
      
    - name: Upload Go binary
      uses: actions/upload-artifact@v3
      with:
        name: go-binary
        path: main
        
  deploy-eks:
    needs: [build-python, build-go]
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Download Python package
      uses: actions/download-artifact@v3
      with:
        name: python-package
        
    - name: Download Go binary  
      uses: actions/download-artifact@v3
      with:
        name: go-binary
        
    - name: Deploy to EKS
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig
        kubectl --kubeconfig=kubeconfig apply -f k8s/
        kubectl --kubeconfig=kubeconfig set image deployment/python-app python-app=myrepo.azurecr.io/python-app:${{ github.sha }}
        kubectl --kubeconfig=kubeconfig set image deployment/go-app go-app=myrepo.azurecr.io/go-app:${{ github.sha }}