name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build Python
        run: |
          python -m compileall .

  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Build Go
        run: go build ./...

  test:
    name: Test Python and Go
    runs-on: ubuntu-latest
    needs: [build, build-go]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python tests
        run: |
          python -m unittest discover tests/python
      - name: Run Go tests
        run: |
          go test ./...

  deploy-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy EKS
        env:
          EKS_CONFIG: ${{ secrets.EKS_CONFIG }}
        run: |
          aws eks create-cluster --cli-input-yaml file://${EKS_CONFIG}
      - name: Deploy API Gateway
        env:
          API_CONFIG: ${{ secrets.API_CONFIG }}
        run: |
          aws apigateway import-rest-api --body file://${API_CONFIG}