name: Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.x'
        
    - name: Install Go dependencies
      run: go get ./...
      
    - name: Run tests
      run: |
        python -m unittest discover tests/
        go test ./...
        
    - name: Build Python app
      run: python setup.py sdist bdist_wheel
      
    - name: Build Go app
      run: go build -o app
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build and push Python image to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/python-app:${{ github.sha }} .
        docker push $ECR_REGISTRY/python-app:${{ github.sha }}
        
    - name: Build and push Go image to Amazon ECR  
      run: |  
        docker build -t $ECR_REGISTRY/go-app:${{ github.sha }} .
        docker push $ECR_REGISTRY/go-app:${{ github.sha }}
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Deploy to EKS
      run: |
        aws eks update-cluster --name clusterchecksdk --region ${{ env.AWS_REGION }}
        kubectl set image deployment/python-app python-app=$ECR_REGISTRY/python-app:${{ github.sha }}
        kubectl set image deployment/go-app go-app=$ECR_REGISTRY/go-app:${{ github.sha }}
        
    - name: Verify deployment    
      run: |
        kubectl get services
        kubectl get pods