name: Deploy to AWS
on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:

  build-python:
    name: Build Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build Python package
      run: python setup.py sdist
    - name: Upload Python package
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: dist/*.tar.gz

  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20.1'
    - name: Build Go package
      run: go build
    - name: Upload Go package
      uses: actions/upload-artifact@v3
      with:
        name: go-package
        path: ./main

  deploy-eks:
    name: Deploy to EKS
    needs: [build-python, build-go]
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Download Python package
      uses: actions/download-artifact@v3
      with:
        name: python-package
    - name: Download Go package  
      uses: actions/download-artifact@v3
      with:
        name: go-package
    - name: Deploy to EKS
      env:
        EKS_CLUSTER_NAME: clusterchecksdk
      run: |
        # Deploy Python and Go packages to EKS
        # Example deployment steps...

  deploy-api-gateway:
    name: Deploy to API Gateway  
    needs: [build-python, build-go]
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy to API Gateway
      env:
        API_GATEWAY_NAME: ghj
      run: |
        # Deploy Python and Go packages to API Gateway
        # Example deployment steps...