AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Project'
          Value: 'CloudGen'
        - Key: 'key'
          Value: 'value'